### PR TITLE
Feature/remove mongodict

### PR DESCRIPTION
**Pull request by flavioamieiro**
This PR removes mongodict from PyPLN. It should be thoroughly review because it introduces quite big changes. It changes the way data is stored in Mongodb and also stops using GridFS. It needs the changes in NAMD/pypln.backend#179 to work, so both these PR should be merged together when they're ready.

### CODE REVIEW

**Comment by fccoelho** [comment]
@flavioamieiro, could you put together a quick step-by-step guide of how to deploy locally for testing?
including how to run the tests.

**Comment by fccoelho** [comment]
BTW, are we still on python 2.7 on this codebase?

**Comment by fccoelho** [comment]
@flavioamieiro I am having trouble installin Pyopenssl on python2 here in my machine.
so if the code is passing all the tests in your setup, I suggest we merge.

**Comment by flavioamieiro** [comment]
@fccoelho All tests are passing, and I've rechecked the code. @israelst did you get a chance to take a quick look at this?

**Comment by israelst** [comment]
Reviewed and tested.
It looks ok for me. :)

**Pull request merged**
