### PR TITLE
Feature/export visualizations

### PR DESCRIPTION
**Pull request by flavioamieiro**
Adds CSV export functionality to most visualizations (there isn't one for 'text' because it does not make sense to export it as CSV).

### CODE REVIEW

**Comment by fccoelho** [comment]
it would be nice to be able to import the csv straight into google fusion tables https://developers.google.com/fusiontables/docs/v1/reference/table/importRows

or google spreadsheets.

but may this should be a separate issue

**Comment by fccoelho** [comment]
One thing people frequently need the full text extraction from PDFs. So I think that we should also offer the option to download an entire corpus as text, tagged text, and possibly other forms. @flavioamieiro: please could you please add that too?

**Comment by turicas** [comment]
@fccoelho, I think this is another feature. In this PR what @flavioamieiro did is to implement extraction of visualizations and we have only document visualizations by now.

**Comment by fccoelho** [comment]
Ok, I'll try to describe it better on a separate issue, so that it can be done as a new feature.

**Pull request merged**
